"""C1 scores (common plan §6.3): each agent run against the draft it started from.

For every run directory of ``c1_run.py`` (``<doc>.<vision>.<effort>.<tag>`` with a ``record.json``): the evaluator's
scores of the draft handed to the agent (``work/fixed``) and of the result (``out``), whole and by page; the process
— runtime, wall time, the agent's tool calls, accepted changes, texts added, review items closed, open items before
and after, tokens, the changes it made against a comparison (``review.agent_overrides``), the hygiene audit.

    uv run python scripts/vision_first/c1_score.py --runs ~/parserx-exp/vision-first-c1/c1b/_c1 \\
        --out eval_runs/2026-09-30_c1_vision_first   # → c1_scores.json, c1_summary.md
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from p0_score import Pages, expected_of, score  # noqa: E402

from parserx.eval.pages import split_pages  # noqa: E402

DOCS = ("paper_chn01", "paper_chn02", "ocr01", "receipt")


def run_scores(runs: Path, out: Path) -> dict:
    pages = Pages()
    table: dict = {"runs": {}}
    for record_path in sorted(runs.glob("*/record.json")):
        record = json.loads(record_path.read_text(encoding="utf-8"))
        if record.get("tag") not in ("r1", "r2"):  # smoke tests
            continue
        run_dir = record_path.parent
        doc = record["doc"]
        info = pages.of(doc)
        expected = expected_of(doc)
        entry = {"record": record}
        for side, path in (("before", run_dir / "work" / "fixed" / f"{doc}.md"), ("after", run_dir / "out" / f"{doc}.md")):
            if path.is_file():
                markdown = path.read_text(encoding="utf-8")
                entry[side] = {"whole": score(markdown, expected, doc),
                               "pages": [score(o, e, f"{doc}#{n}")["key_errors"] for n, (e, o) in
                                         enumerate(zip(info["expected"], split_pages(markdown, info["texts"])), 1)]}
        summary = run_dir / "out" / f"{doc}.json"
        if summary.is_file():
            review = json.loads(summary.read_text(encoding="utf-8"))["review"]
            entry["overrides"] = review.get("agent_overrides", [])
            entry["open_after_by_kind"] = review.get("by_kind", {})
        table["runs"][run_dir.name] = entry
    out.mkdir(parents=True, exist_ok=True)
    (out / "c1_scores.json").write_text(json.dumps(table, ensure_ascii=False, indent=1), encoding="utf-8")
    (out / "c1_summary.md").write_text(summary_md(table), encoding="utf-8")
    return table


def summary_md(table: dict) -> str:
    rows = defaultdict(list)
    for name, entry in table["runs"].items():
        r = entry["record"]
        rows[(r["doc"], r["vision"], r["effort"])].append((name, entry))
    out = ["# C1 summary (generated by c1_score.py)", "",
           "| document | vision | effort | run | runtime | key errors before → after | char_f1 | headings | tables "
           "| formulas sim | by page (after) | s | calls | changes | added | closed | open before → after "
           "| overrides | tokens in/out | audit |",
           "|" + "---|" * 20]
    for (doc, vision, effort) in sorted(rows, key=lambda k: (DOCS.index(k[0]) if k[0] in DOCS else 9, k[1], k[2])):
        for name, entry in sorted(rows[(doc, vision, effort)]):
            r, a = entry["record"], entry["record"].get("agent") or {}
            b, f = entry.get("before", {}).get("whole", {}), entry.get("after", {}).get("whole", {})
            usage = r.get("usage") or {}
            out.append(
                f"| {doc} | {vision} | {effort} | {r['tag']} | {r['runtime']} | {b.get('key_errors')} → "
                f"{f.get('key_errors')} | {_f(b.get('char_f1'))} → {_f(f.get('char_f1'))} | "
                f"{_f(b.get('heading_f1'))} → {_f(f.get('heading_f1'))} | {_f(b.get('table_f1'))} → "
                f"{_f(f.get('table_f1'))} | {_f(b.get('formula_similarity'))} → {_f(f.get('formula_similarity'))} | "
                f"{' '.join(map(str, entry.get('after', {}).get('pages', [])))} | {r.get('seconds')} | "
                f"{a.get('tool_calls')} | {a.get('changes')} | {a.get('added')} | {a.get('closed')} | "
                f"{a.get('review_open_before')} → {a.get('review_open_after')} | {len(entry.get('overrides', []))} | "
                f"{usage.get('input_tokens')}/{usage.get('output_tokens')} | "
                f"{'ok' if not r.get('audit') or r['audit'].get('ok') else 'HITS'} |")
    return "\n".join(out) + "\n"


def _f(v) -> str:
    return "—" if v is None else f"{v:.3f}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--runs", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    run_scores(args.runs.expanduser(), args.out)
    print((args.out / "c1_summary.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
