"""P0 number audit (execution plan §3.3, the stop condition): number changes the comparison did not find.

``copy`` and ``table`` parts place the text layer as it is, so a number can change only in a ``write`` part, and
every write part is compared with the lines it replaces (``p0_score.written_checks``).  From the other side: a
number the page's output has more often than both M's page and the annotation (introduced), or less often than both
(dropped), is looked up in the write parts; one that no write part with a flagged difference holds is listed as
**unflagged** for a look at the page.  Numbers are the evaluator's number tokens (``extract_key_tokens``).

    uv run python scripts/vision_first/p0_numbers.py --run-dir eval_runs/<run>   # → <run-dir>/numbers.json, .md
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import p0_contract as contract  # noqa: E402
from p0_inputs import PAGES, load, page_id  # noqa: E402
from p0_run import CONFIGS  # noqa: E402
from p0_score import Pages  # noqa: E402

from parserx.eval.key_content import extract_key_tokens  # noqa: E402


def tokens(md: str) -> Counter:
    return Counter(map(str, extract_key_tokens(md)["number"]))


def audit(run_dir: Path) -> dict:
    pages = Pages()
    out: dict = {}
    for doc, n in PAGES:
        pid = page_id(doc, n)
        page = load(run_dir, pid)
        info = pages.of(doc)
        expected, m_page = tokens(info["expected"][n - 1]), tokens(info["arms"]["M"][n - 1])
        text_of = {f"L{k}": line["text"] for k, line in enumerate(page["lines"], 1)}
        for name, *_ in CONFIGS:
            path = run_dir / "results" / name / f"{pid}.json"
            if not path.exists():
                continue
            result = json.loads(path.read_text(encoding="utf-8"))
            ours = tokens(result["markdown"])
            introduced = {t: c - max(m_page[t], expected[t]) for t, c in ours.items() if c > max(m_page[t], expected[t])}
            dropped = {t: min(m_page[t], expected[t]) - ours[t] for t in set(m_page) | set(expected)
                       if ours[t] < min(m_page[t], expected[t])}
            writes = []
            for block in result["final"]["data"]["blocks"]:
                for part in block["parts"]:
                    if part["kind"] != "write":
                        continue
                    names = [f"L{k}" for ref in part["lines"] for k in contract.expand(ref) or []]
                    original = tokens("\n".join(text_of.get(x, "") for x in names)) if names else Counter()
                    written = tokens(part["text"])
                    writes.append({"block": block["id"], "written": written, "original": original,
                                   "flagged": bool(names) and written != original, "free": not names})
            rows = []
            for kind, found in (("introduced", introduced), ("dropped", dropped)):
                for token, count in sorted(found.items()):
                    holders = [w for w in writes if (w["written"] if kind == "introduced" else w["original"])[token]]
                    rows.append({"kind": kind, "number": token, "count": count,
                                 "flagged_in": [w["block"] for w in holders if w["flagged"]],
                                 "written_free": [w["block"] for w in holders if w["free"]],
                                 "unflagged": not any(w["flagged"] for w in holders)})
            out.setdefault(pid, {})[name] = rows
    return out


def report(found: dict) -> str:
    lines = ["# P0 number audit (generated by p0_numbers.py)", "",
             "Numbers the page output has beyond both M's page and the annotation (introduced) or lacks that both "
             "have (dropped); *unflagged* = no write part with a flagged difference holds it.", "",
             "| page | configuration | introduced (flagged / unflagged) | dropped (flagged / unflagged) |",
             "|---|---|---|---|"]
    for pid, by in found.items():
        for name, rows in by.items():
            if not rows:
                continue
            cell = lambda k, f: ", ".join(f"{r['number']}×{r['count']}" for r in rows if r["kind"] == k and r["unflagged"] != f) or "—"  # noqa: E731
            lines.append(f"| {pid} | {name} | {cell('introduced', True)} / **{cell('introduced', False)}** | "
                         f"{cell('dropped', True)} / **{cell('dropped', False)}** |")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run-dir", type=Path, required=True)
    args = parser.parse_args()
    found = audit(args.run_dir)
    (args.run_dir / "numbers.json").write_text(json.dumps(found, ensure_ascii=False, indent=1), encoding="utf-8")
    text = report(found)
    (args.run_dir / "numbers.md").write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
