"""V scores (common plan §6.2, §6.4, §6.5): whole documents and their pages, paired with the other groups.

For every V output (``<run-dir>/docs/<configuration>/<document>/<document>.md``) and every comparison group on the
benchmark table (M, R, L, the hybrid runtime, Datalab …): the evaluator's scores of the whole document, the key
content classes also as multisets, headings and formulas; per page the key errors of the pages V sent (the
annotation and each output cut into pages the same way); routing, cost and time from ``v_record.json``.

    uv run python scripts/vision_first/v_score.py --run-dir eval_runs/<run>   # → v_scores.json, v_summary.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from p0_inputs import document  # noqa: E402
from p0_score import BAG_KINDS, Pages, score  # noqa: E402

from parserx.eval.pages import split_pages  # noqa: E402

BENCH = REPO_ROOT / "eval_runs" / "bench"
GROUPS = {"M": "parserx-fixed", "R": "parserx-fixed-R", "L": "llamaparse-agentic", "hybrid": "parserx-hybrid",
          "Datalab": "datalab-accurate"}


def run_score(run_dir: Path) -> dict:
    pages = Pages()
    table: dict = {"documents": {}}
    for doc_dir in sorted({p.parent.name for p in (run_dir / "docs").glob("*/*/v_record.json")}):
        doc = doc_dir
        if not (document(doc).parent / "expected.md").exists():  # no annotation: nothing to score against
            continue
        expected = (document(doc).parent / "expected.md").read_text(encoding="utf-8")
        info = pages.of(doc) if document(doc).suffix.lower() == ".pdf" else None
        entry: dict = {"groups": {}, "configs": {}}
        for label, tool in GROUPS.items():
            out = BENCH / tool / doc / "output.md"
            if out.exists():
                entry["groups"][label] = _scored(out.read_text(encoding="utf-8"), expected, doc, info)
        for record_path in sorted((run_dir / "docs").glob(f"*/{doc}/v_record.json")):
            record = json.loads(record_path.read_text(encoding="utf-8"))
            markdown = (record_path.parent / f"{doc}.md").read_text(encoding="utf-8")
            entry["configs"][record["configuration"]] = {**_scored(markdown, expected, doc, info), "record": record}
        table["documents"][doc] = entry
    (run_dir / "v_scores.json").write_text(json.dumps(table, ensure_ascii=False, indent=1), encoding="utf-8")
    (run_dir / "v_summary.md").write_text(summary(table), encoding="utf-8")
    return table


def _scored(markdown: str, expected: str, doc: str, info: dict) -> dict:
    whole = score(markdown, expected, doc)
    by_page = [score(o, e, f"{doc}#{n}")["key_errors"]
               for n, (e, o) in enumerate(zip(info["expected"], split_pages(markdown, info["texts"])), 1)] if info else []
    return {"whole": whole, "pages": by_page}


def summary(table: dict) -> str:
    out = ["# V summary (generated by v_score.py)", ""]
    for doc, entry in table["documents"].items():
        rows = [(k, v) for k, v in entry["groups"].items()] + [(k, v) for k, v in entry["configs"].items()]
        sent = next(iter(entry["configs"].values()), {}).get("record", {}).get("routed", {})
        out += [f"## {doc}", "", f"Pages sent: {', '.join(f'{n} ({', '.join(why)})' for n, why in sent.items()) or 'none'}", "",
                "| group | key errors | multiset (num/unit/sign/script) | char_f1 | headings | tables | formulas paired, similarity "
                "| lost runs (chars) | key errors by page | $ (allocation + pipeline) | s |",
                "|---|---|---|---|---|---|---|---|---|---|---|"]
        for label, value in rows:
            w = value["whole"]
            bag = sum(w["bag_missing"][k] + w["bag_extra"][k] for k in BAG_KINDS)
            record = value.get("record")
            cost = (f"{record['allocation_usd']} + {record['pipeline_usd']}" if record else "—")
            seconds = record["seconds"] if record else "—"
            out.append(f"| {label} | {w['key_errors']} | {bag} | {w['char_f1']:.3f} | {_f(w['heading_f1'])} | "
                       f"{_f(w['table_f1'])} | {w['formulas_paired'] or 0}/{w['formulas_expected'] or 0}, "
                       f"{_f(w['formula_similarity'])} | {w['lost_runs']} ({w['lost_chars']}) | "
                       f"{' '.join(map(str, value['pages']))} | {cost} | {seconds} |")
        out.append("")
    return "\n".join(out) + "\n"


def _f(v) -> str:
    return "—" if v is None else f"{v:.3f}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run-dir", type=Path, required=True)
    args = parser.parse_args()
    run_score(args.run_dir)
    print((args.run_dir / "v_summary.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
